name: DependencyTrackerWorkFlow

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          Label: ${{ startsWith(github.ref, 'refs/tags') && github.ref_name ||  format('{0}-{1}', github.ref_name, github.SHA)  }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'corretto'
                server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
                settings-path: ${{ github.workspace }} # location for the settings.xml file.
            - name: compile project
              run: ./mvnw compile
            # Generates a BoM and uploads it to OWASP Dependency Track
            - name: Generates BoM and upload to OWASP Dependency Tracker
              id: riskscoreFromDT
              uses:  DependencyTrack/gh-upload-sbom@@master
              with:
                serverhostname: 'dependencytracker.endios.one'
                port: 8080
                protocol: 'http'
                bomfilename: 'target/bom.xml'
                apikey: ${{ secrets.OWASP_DEPENDENCY_TRACKER_KEY }}
                projectname: 'Example Project'
                projectversion: ${{ env.Label }}
