name: DependencyTrackerMasterWorkFlow
on:
  push:
    branches:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action development
        if: github.ref_name == 'development'
        run: |
            echo "it is the Development branch value of ref_name is:  ${{ github.ref_name }}"
      - name: Print GitHub event action main
        if: github.ref_name == 'main'
        run: |
          echo "it is the Main branch value of ref_name is: ${{ github.ref_name }}"
