name: DependencyTrackerMasterWorkFlow
on:
  push:
    branches:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub event action
        run: |
            echo "${{ github.event.action }} - ${{ github.event_name }} - ${{ github.ref_name }}"
