name: Deploy master
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Which Environment to deploy to'
        options: 
        - test
        - prod
        - test-and-prod

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: log a message test-and-prod
      if: inputs.environment == 'test-and-prod'
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to test-and-prod ${{ github.sha }}"
    - name: log a message test
      if: inputs.environment == 'test'
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to test ${{ github.sha }}"
    - name: log a message prod
      if: inputs.environment == 'prod'
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to prod ${{ github.sha }}"
  report-error:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: log a message
      run: echo "::error file=deploy-main.yml,line=6,col=5,endColumn=50::You can only run the deploy workflow on a release tag. ${{ github.sha }}"
    - name: Exit
      run: exit 1
