name: Deploy master
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Which Environment to deploy to'
        options: 
        - test
        - prod
        - test-and-prod

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      Label: ${{ startsWith(github.ref, 'refs/tags') && github.ref_name ||  format('{0}-{1}', github.ref_name, github.SHA)  }}
    steps:
    - name: ${{$Label}}
      run: echo "The label is $Label"
    - name: Check is it a production deployment?
      if: ${{ (inputs.environment == 'test-and-prod' || inputs.environment == 'prod') && !startsWith(github.ref, 'refs/tags') }}
      run: |
        echo "::error file=deploy-main.yml,line=19,col=7,endColumn=129::You can only run the deploy workflow on a release tag for production deployment."
        exit 1
    - name: log a message test-and-prod
      if: inputs.environment == 'test-and-prod'
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to test-and-prod ${{ github.sha }}"
    - name: log a message test
      if: inputs.environment == 'test'
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to test ${{ github.sha }}"
    - name: log a message prod
      if: inputs.environment == 'prod'
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to prod ${{ github.sha }}"
