name: Deploy master
on: 
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Which Environment to deploy to'
        options: 
        - test
        - prod
        - test-and-prod

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: log a message
      run: echo "it is a tag ${{ github.ref_name }}.zip to be deployed to ${{ inputs.environment == 'test-and-prod'}}"
  report-error:
    if: ${{ !startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: log a message
      run: echo "::error file=deploy-main.yml,line=6,col=5,endColumn=50::You can only run the deploy workflow on a release tag."
    - name: Exit
      run: exit 1
