name: Deploy master
on: [workflow_dispatch]

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
    - name: log a message
      run: echo "it is a tag"
  build2:
    runs-on: ubuntu-latest
    steps:
    - name: log a message
      run: echo ${{ github.ref }}
